jobs:
 - job: Windows
   pool: 'Hosted VS2017'
   strategy:
     matrix:
       node_8_x:
          test_suite: simple
          node_version: 8.x
       node_10_x:
          node_version: 10.x
   steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(node_version)
      displayName: 'Install Node.js'

    - bash: |
        export PATH="$HOME/.yarn/bin:$PATH"
        echo $TEST_SUITE
      displayName: 'Install yarn'

    - bash: |
        echo testing
      displayName: 'install and build'
