jobs:
 - job: Windows
   pool: 'Hosted VS2017'
   strategy:
     matrix:
       node_8_x:
          test_suite: simple
          node_version: 8.x
       node_10_x:
          node_version: 10.x
   steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(node_version)
      displayName: 'Install Node.js'

    - bash: |
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
        export PATH="$HOME/.yarn/bin:$PATH"
        echo $test_suite '-' $node_version
      displayName: 'install yarn'
      env: { TEST_SUITE:  $(test_suite) }

    - bash: |
        echo testing
      displayName: 'install and build'
      env: { TEST_SUITE:  $(test_suite) }
